### ISSUE TITLE
Front and backend dev: TOS opt-in and version tracking

### ISSUE THREAD

**Issue by jel535s** [MidwestAccessCoalition/lockbox_rails#608]
## Context
Blocked by #539 
Once the Terms of Service (TOS) is live in the footer of the app, we want users to be triggered to read the TOS and agree to it, upon their next log in. We also need to build a framework to record which version of the TOS they see, in case of future versioning for the TOS.

## Process
Build a pop-up message that shows the TOS link, and asks the user to agree to the TOS with two call to action buttons: "I agree" or "I do not agree". Clicking "I do not agree" will log the user out of the app.
**Copy for pop-up: @jasonwynkoop86 or TJ, please provide UX-friendly copy here!**
The link should open in a new browser window.
This pop-up should only display once, the next time a user logs in. Maybe this will require adding a field to the user database that tracks whether or not they have agreed to the TOS? Maybe there is a better way to make sure this pop-up only displays once and not every time the user logs in? Or add a new disclosure table to track which version of the TOS that the user or IP address accessed and agreed to. If you're not sure of the best way to build this, bring it up in the stand or during working hours and we'll chat it out.

## Acceptance Criteria/Definition of Done

- [ ] When a user logs in, they should see a pop up that shows the TOS link and asks them to agree to the TOS. 
- [ ] The link should open in a new browser window.
- [ ] This pop-up should only display once, the next time a user logs in.

**Comment by jasonwynkoop86** [comment]
How does this look? 
![MacBook Pro - 1](https://user-images.githubusercontent.com/82782739/121817963-06489b80-cc4a-11eb-8b50-862b97aafdb4.png)
Same lockbox blue at 60% shades the background. 

TERMS OF SERVICE

Lockbox has updated its terms of service. Please click the link below to read the new Terms of Service and Privacy Policy agreements. 

All users must agree to the terms to use the service. If you do not agree, you will be logged out.  

Accept and proceed in a button
Decline and logout as red link text.
